db.sales.aggregate([
    {
        $unwind: "$items"
    },
    {
        $group: {
            _id: {
                store: "$store",
                month: { $dateToString: { format: "%Y-%m", date: "$date" } }
            },
            totalRevenue: { $sum: { $multiply: ["$items.quantity", "$items.price"] } },
            averagePrice: { $avg: "$items.price" }
        }
    },
    {
        $project: {
            store: "$_id.store",
            month: "$_id.month",
            totalRevenue: 1,
            averagePrice: { $round: ["$averagePrice", 2] }
        }
    },
    {
        $sort: {
            store: 1,
            month: 1
        }
    }
])

/*first unwind items then group with store and month with date format
totalRevenue: The total revenue generated by multiplying the quantity of each item sold by its price.
averagePrice: The average price of items sold during that month.
project is used to define desired output
Finally, sort the results first by store in ascending order and then by month,  
*/
